@startuml
title
<font size=18 color=black>Діаграма прецедентів
end title

actor "Користувач" as User
actor "Привілейований користувач" as superUser

usecase "<b>UC_1</b>\nКупити привілейований\n доступ" as UC_1
usecase "<b>UC_2</b>\nПрочитати документацію" as UC_2
usecase "<b>UC_3</b>\nВідправити запит (Web)" as UC_3
usecase "<b>UC_4</b>\nВідправити запит (API)" as UC_4
usecase "<b>UC_5</b>\nОбрати глибину\n вкладеності" as UC_5

User --> UC_1
User --> UC_2
User --> UC_3
User --> UC_4

superUser --|> User
superUser --> UC_5
@enduml
