@startuml

left header
<font color=000 size=16><b>ID:</b> UC_1
<font color=000 size=16><b>Назва:</b> Купити привілейований доступ
<font color=000 size=16><b>Учасники:</b> Користувач, Система(Web)
<font color=000 size=16><b>Передумови:</b> Користувач не має привілейованого доступу
<font color=000 size=16><b>Результат:</b> Отримання статусу привілейованого статусу
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=red size=16>EX_U1, EX_S1

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Натискає на кнопку
"Отримати pro-версію";

|Система(Web)|
: Перенаправляє користувача
 на сторінку з оплатою;

|Користувач|
: Вводить адресу
електронної пошти;
note right #ffaaaa
<b> Можливо
<b> EX_U1
end note

: Вибирає спосіб оплати;
note right
<b> Оплачує через
<b> стороннє ПЗ
end note

|Система(Web)|
:Створює унікальний ключ
привілейованого доступу;

:Відправляє ключ на почту;
note left #ffaaaa
<b> Можливо
<b> EX_S1
end note

|Користувач|
stop;

@enduml
