@startuml

left header
<font color=000 size=16><b>ID:</b> UC_3
<font color=000 size=16><b>Назва:</b> Відправити запит(Web)
<font color=000 size=16><b>Учасники:</b> Користувач, Система(Web), Система(CytrusAPI)
<font color=000 size=16><b>Передумови:</b>
<font color=000 size=16><b>Результат:</b> Користувач отримав дані
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=red size=16>EX_U2, EX_U4

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Заповнює текстове поле;
note right
<b> Необов'язково
end note

: Обирає формат відповіді;
note right
<b> За замовчуванням
<b> JSON
end note

:Відправляє запит мовою Cypher;


|Система(Web)|
: Аналізує запит користувача;
note left #ffaaaa
<b> Можливо
<b> EX_U2
end note

:Перенаправляє запит до CytrusAPI;

|Система(CytrusAPI)|
:Аналізує запит користувача;
note left
<b> Помилки EX_U2 не буде,
<b> бо пройдена валідація
<b> на Web-сторінці
end note

:Відправляє текст до API
    аналізу текстів;
note left
<b> Необов'язково
end note

:Робить запит до бази даних;
note left #ffaaaa
<b> Можливо
<b> EX_U4
end note

:Формує відповідь в обраному
Користувачем форматі;

:Відправляє відповідь на Web-сторінку;

|Система(Web)|
:Відображає відповідь сервера Користувачу;

|Користувач|
stop;

@enduml