@startuml

left header
<font color=000 size=16><b>ID:</b> UC_4.1
<font color=000 size=16><b>Назва:</b> Відправити запит(API)
<font color=000 size=16><b>Учасники:</b> Користувач(СПЗ), Система(CytrusAPI)
<font color=000 size=16><b>Передумови:</b>
<font color=000 size=16><b>Результат:</b> Користувач отримав дані
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=red size=16>EX_U2, EX_U4, EX_U5

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Формує запит;
note right
<b> Задає текст(необов'язково)
<b> Задає формат відповіді
(За замовчуванням JSON)
<b> Задає запит(мовою Cytrus)
end note

:Відправляє запит до CytrusAPI;

|Система(CytrusAPI)|
:Аналізує запит користувача;
note left #ffaaaa
<b> Можливо
<b> EX_U2, EX_U5
end note

:Відправляє текст до API
    аналізу текстів;
note left
<b> Необов'язково
end note

:Робить запит до бази даних;
note left #ffaaaa
<b> Можливо
<b> EX_U4
end note

:Формує відповідь в обраному
Користувачем форматі;

:Відправляє відповідь Користувачу;


|Користувач|
:Отримує дані;
stop;


@enduml
